# permissions for end users to edit mosquittoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: mosquitto-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: mosquitto-operator
    app.kubernetes.io/part-of: mosquitto-operator
    app.kubernetes.io/managed-by: kustomize
  name: mosquitto-editor-role
rules:
- apiGroups:
  - messaging.eclipse.org
  resources:
  - mosquittoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - messaging.eclipse.org
  resources:
  - mosquittoes/status
  verbs:
  - get
