apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.Name }}
  namespace: {{ .Values.Namespace }}
data:
  mosquitto.conf: |
    # Port for plaintext communication
    listener 1883
    
    # Port and certificates for TLS encrypted communication
    # listener 8883
    # certfile /myuser/server.crt
    # cafile /myuser/ca.crt
    # keyfile /myuser/server.key
    {{if .Values.AuthEnabled}}
    password_file /myuser/passwd
    {{else}}
    allow_anonymous true
    {{end}}
